services:
  - type: web
    name: lunghealth
    env: python
    repo: https://github.com/rose-kaks/LungHealth
    branch: main
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: POETRY_VERSION
        value: 1.7.1